# Generated by Django 4.0.4 on 2022-06-27 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 16, 17, 31, 301487, tzinfo=utc), verbose_name='date created'),
        ),
    ]
