# Generated by Django 4.0.4 on 2022-06-27 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0005_alter_status_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 17, 4, 32, 273917, tzinfo=utc), null=True, verbose_name='Дата создания'),
        ),
    ]
