# Generated by Django 4.0.4 on 2022-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0007_alter_status_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Имя'),
        ),
    ]
